// BIR Form Assistant — mock copy of Dev A's field schemas, for mock mode only.
//
// Generated from backend/app/Services/BIR/Schemas (Form1601CSchema, Form2316Schema).
// The real list should come from GET /bir/config (schemas) — this file stands in
// until it does, and is removed with birFixtures.js in Week 7. Do not edit by hand:
// regenerate it if the PHP schemas change.

// [key, item, label, type, source, required]
const rows = {
  '1601-C': [
    ["return_period","1","For the Month (MM/YYYY)","month","user",true],
    ["is_amended","2","Amended Return?","boolean","user",true],
    ["has_taxes_withheld","3","Any Taxes Withheld?","boolean","payroll",true],
    ["sheets_attached","4","Number of Sheet/s Attached","integer","user",true],
    ["atc_code","5","ATC","string","settings",true],
    ["company_tin","6","Taxpayer Identification Number (TIN)","string","settings",true],
    ["rdo_code","7","RDO Code","string","settings",true],
    ["company_name","8","Withholding Agent's Name (Last, First, Middle for Individual OR Registered Name for Non-Individual)","string","settings",true],
    ["company_address","9","Registered Address","text","settings",true],
    ["company_zip","9A","ZIP Code","string","settings",true],
    ["company_contact_number","10","Contact Number","string","settings",false],
    ["agent_category","11","Category of Withholding Agent","enum","settings",true],
    ["company_email","12","Email Address","string","settings",false],
    ["has_tax_relief","13","Are there payees availing of tax relief under Special Law or International Tax Treaty?","boolean","user",false],
    ["tax_relief_details","13A","If yes, specify","text","user",false],
    ["total_compensation","14","Total Amount of Compensation","decimal","payroll",true],
    ["mwe_statutory_wage","15","Statutory Minimum Wage for Minimum Wage Earners (MWEs)","decimal","payroll",true],
    ["mwe_premium_pay","16","Holiday Pay, Overtime Pay, Night Shift Differential Pay, Hazard Pay (for MWEs only)","decimal","payroll",true],
    ["thirteenth_month_and_benefits","17","13th Month Pay and Other Benefits","decimal","payroll",true],
    ["de_minimis_benefits","18","De Minimis Benefits","decimal","payroll",true],
    ["statutory_contributions_ee","19","SSS, GSIS, PHIC, HDMF Mandatory Contributions & Union Dues (employee's share only)","decimal","payroll",true],
    ["other_nontaxable_compensation","20","Other Non-Taxable Compensation (specify)","decimal","user",false],
    ["other_nontaxable_compensation_desc","20","Other Non-Taxable Compensation — description","string","user",false],
    ["total_nontaxable_compensation","21","Total Non-Taxable Compensation (Sum of Items 15 to 20)","decimal","payroll",true],
    ["total_taxable_compensation","22","Total Taxable Compensation (Item 14 Less Item 21)","decimal","payroll",true],
    ["exempt_250k_compensation","23","Less: Taxable compensation not subject to withholding tax (non-MWE, P250,000 & below for the year)","decimal","payroll",true],
    ["net_taxable_compensation","24","Net Taxable Compensation (Item 22 Less Item 23)","decimal","payroll",true],
    ["total_taxes_withheld","25","Total Taxes Withheld","decimal","payroll",true],
    ["prior_month_adjustment","26","Add/(Less): Adjustment of Taxes Withheld from Previous Month/s (from Part IV Schedule 1, Item 4)","decimal","user",false],
    ["taxes_withheld_for_remittance","27","Taxes Withheld for Remittance (Sum of Items 25 and 26)","decimal","payroll",true],
    ["previously_remitted_tax","28","Less: Tax Remitted in Return Previously Filed, if this is an amended return","decimal","user",false],
    ["other_remittances","29","Other Remittances Made (specify)","decimal","user",false],
    ["other_remittances_desc","29","Other Remittances Made — description","string","user",false],
    ["total_remittances_made","30","Total Tax Remittances Made (Sum of Items 28 and 29)","decimal","payroll",false],
    ["tax_still_due","31","Tax Still Due/(Over-remittance) (Item 27 Less Item 30)","decimal","payroll",true],
    ["surcharge","32","Surcharge","decimal","user",false],
    ["interest","33","Interest","decimal","user",false],
    ["compromise","34","Compromise","decimal","user",false],
    ["total_penalties","35","Total Penalties (Sum of Items 32 to 34)","decimal","payroll",true],
    ["total_amount_due","36","TOTAL AMOUNT STILL DUE/(Over-remittance) (Sum of Items 31 and 35)","decimal","payroll",true],
  ],
  '2316': [
    ["tax_year","1","For the Year (YYYY)","integer","user",true],
    ["period_from","2","For the Period From (MM/DD)","string","user",false],
    ["period_to","2","For the Period To (MM/DD)","string","user",false],
    ["employee_tin","3","TIN","string","payroll",true],
    ["employee_last_name","4","Employee's Name — Last Name","string","payroll",true],
    ["employee_first_name","4","Employee's Name — First Name","string","payroll",true],
    ["employee_middle_name","4","Employee's Name — Middle Name","string","user",false],
    ["employee_rdo_code","5","RDO Code","string","user",true],
    ["basic_salary_annual",null,"Basic Salary (incl. the exempt P250,000 & below, or the Statutory MW of the MWE)","decimal","payroll",true],
    ["employee_registered_address","6","Registered Address","text","user",true],
    ["employee_registered_zip","6A","ZIP Code","string","user",false],
    ["employee_home_address","6B","Local Home Address","text","user",false],
    ["employee_home_zip","6C","ZIP Code","string","user",false],
    ["employee_foreign_address","6D","Foreign Address","text","user",false],
    ["employee_birthdate","7","Date of Birth (MM/DD/YYYY)","date","user",true],
    ["employee_contact_number","8","Contact Number","string","payroll",false],
    ["mwe_daily_rate","9","Statutory Minimum Wage rate per day","decimal","user",false],
    ["mwe_monthly_rate","10","Statutory Minimum Wage rate per month","decimal","user",false],
    ["is_mwe","11","Minimum Wage Earner (MWE) whose compensation is exempt from withholding tax","boolean","user",true],
    ["present_employer_tin","12","TIN","string","settings",true],
    ["present_employer_name","13","Employer's Name","string","settings",true],
    ["present_employer_address","14","Registered Address","text","settings",true],
    ["present_employer_zip","14A","ZIP Code","string","settings",true],
    ["employer_type","15","Type of Employer","enum","settings",true],
    ["has_previous_employer",null,"Had another employer earlier in the year","boolean","user",false],
    ["previous_employer_tin","16","TIN","string","user",false],
    ["previous_employer_name","17","Employer's Name","string","user",false],
    ["previous_employer_address","18","Registered Address","text","user",false],
    ["previous_employer_zip","18A","ZIP Code","string","user",false],
    ["gross_compensation_present","19","Gross Compensation Income from Present Employer (Sum of Items 38 and 52)","decimal","payroll",true],
    ["less_nontaxable_present","20","Less: Total Non-Taxable/Exempt Compensation Income from Present Employer (from Item 38)","decimal","payroll",true],
    ["taxable_income_present","21","Taxable Compensation Income from Present Employer (Item 19 Less Item 20) (from Item 52)","decimal","payroll",true],
    ["taxable_income_previous_employer","22","Add: Taxable Compensation Income from Previous Employer, if applicable","decimal","user",false],
    ["gross_taxable_income","23","Gross Taxable Compensation Income (Sum of Items 21 and 22)","decimal","payroll",true],
    ["tax_due","24","Tax Due","decimal","payroll",true],
    ["taxes_withheld_present","25A","Amount of Taxes Withheld — Present Employer","decimal","payroll",true],
    ["taxes_withheld_previous","25B","Amount of Taxes Withheld — Previous Employer, if applicable","decimal","user",false],
    ["total_taxes_withheld_adjusted","26","Total Amount of Taxes Withheld as adjusted (Sum of Items 25A and 25B)","decimal","payroll",true],
    ["pera_tax_credit","27","5% Tax Credit (PERA Act of 2008)","decimal","user",false],
    ["total_taxes_withheld_final","28","Total Taxes Withheld (Sum of Items 26 and 27)","decimal","payroll",true],
    ["nontax_mwe_basic","29","Basic Salary (including the exempt P250,000 & below) or the Statutory Minimum Wage of the MWE","decimal","payroll",false],
    ["nontax_mwe_holiday","30","Holiday Pay (MWE)","decimal","payroll",false],
    ["nontax_mwe_overtime","31","Overtime Pay (MWE)","decimal","payroll",false],
    ["nontax_mwe_night_diff","32","Night Shift Differential (MWE)","decimal","payroll",false],
    ["nontax_mwe_hazard","33","Hazard Pay (MWE)","decimal","payroll",false],
    ["nontax_thirteenth_month","34","13th Month Pay and Other Benefits (maximum of P90,000)","decimal","payroll",true],
    ["nontax_de_minimis","35","De Minimis Benefits","decimal","payroll",false],
    ["nontax_statutory_contributions","36","SSS, GSIS, PHIC & PAG-IBIG Contributions and Union Dues (Employee share only)","decimal","payroll",true],
    ["nontax_other_mwe_compensation","37","Salaries and Other Forms of Compensation","decimal","payroll",false],
    ["nontax_total","38","Total Non-Taxable/Exempt Compensation Income (Sum of Items 29 to 37)","decimal","payroll",true],
    ["tax_basic_salary","39","Basic Salary","decimal","payroll",true],
    ["tax_representation","40","Representation","decimal","payroll",false],
    ["tax_transportation","41","Transportation","decimal","payroll",false],
    ["tax_cola","42","Cost of Living Allowance (COLA)","decimal","payroll",false],
    ["tax_housing","43","Fixed Housing Allowance","decimal","payroll",false],
    ["tax_others_44a_desc","44A","Others (specify), row A","string","user",false],
    ["tax_others_44a_amount","44A","Others, row A — amount","decimal","user",false],
    ["tax_others_44b_desc","44B","Others (specify), row B","string","user",false],
    ["tax_others_44b_amount","44B","Others, row B — amount","decimal","user",false],
    ["tax_commission","45","Commission","decimal","payroll",false],
    ["tax_profit_sharing","46","Profit Sharing","decimal","payroll",false],
    ["tax_directors_fees","47","Fees Including Director's Fees","decimal","payroll",false],
    ["tax_thirteenth_month_excess","48","Taxable 13th Month Benefits","decimal","payroll",true],
    ["tax_hazard_pay","49","Hazard Pay","decimal","payroll",false],
    ["tax_overtime","50","Overtime Pay","decimal","payroll",false],
    ["tax_others_51a_desc","51A","Others (specify), row A","string","user",false],
    ["tax_others_51a_amount","51A","Others, row A — amount","decimal","user",false],
    ["tax_others_51b_desc","51B","Others (specify), row B","string","user",false],
    ["tax_others_51b_amount","51B","Others, row B — amount","decimal","user",false],
    ["tax_regular_total","52","Total Taxable Compensation Income Regular (Sum of Items 39 to 51B)","decimal","payroll",true],
    ["is_substituted_filing",null,"Qualified under substituted filing of ITR","boolean","user",false],
    ["employer_signature_date","53","Present Employer/Authorized Agent Signature over Printed Name, Date Signed","date","user",false],
    ["employee_signature_date","54","Employee Signature over Printed Name (CONFORME), Date Signed","date","user",false],
    ["substituted_employer_signature","55","Present Employer/Authorized Agent Signature over Printed Name (substituted filing)","manual","manual",false],
    ["substituted_employee_signature","56","Employee Signature over Printed Name (substituted filing)","manual","manual",false],
    ["employee_ctc_or_id",null,"CTC/Valid ID No. of Employee","string","user",false],
    ["ctc_place_of_issue",null,"Place of Issue","string","user",false],
    ["ctc_date_issued",null,"Date Issued (CTC/Valid ID)","date","user",false],
    ["ctc_amount_paid",null,"Amount paid, if CTC","decimal","user",false],
  ],
}

export const birMockSchemas = Object.fromEntries(
  Object.entries(rows).map(([form, list]) => [
    form,
    list.map(([key, item, label, type, source, required]) => ({ key, item, label, type, source, required })),
  ]),
)