map $http_x_forwarded_proto $fwd_proto {
    default $http_x_forwarded_proto;
    ""      $scheme;
}

map $http_x_forwarded_port $fwd_port {
    default $http_x_forwarded_port;
    ""      $server_port;
}

server {
    listen 80;
    server_name _;
    client_max_body_size 12m;
    root /var/www/frontend/dist;
    index index.html;

    location /api {
        include /etc/nginx/php-fastcgi.conf;
    }

    location /up {
        include /etc/nginx/php-fastcgi.conf;
    }

    location /sanctum {
        include /etc/nginx/php-fastcgi.conf;
    }

    include /etc/nginx/spa-cache.nginx.conf;
}
